### ISSUE TITLE
Timeline monitoring do not display data bubbles 

### ISSUE THREAD

**Issue by jre3brg** [Icinga/icingaweb2#4887]
## Describe the bug
Timeline monitoring option do not display any bubble showing the relevant data for notification, downtimes, state changes, etc.

## To Reproduce
https://icingawebhost/monitoring/timeline

## Expected behavior
Expected to be displayed data bubbles

## Your Environment

* Icinga Web 2 version and modules (System - About): 2.11.1
* Web browser used: Google Chrome | 103.0.5060.114
* Icinga 2 version used (`icinga2 --version`): r2.13.4-1
* PHP version used (`php --version`): 7.3.29
* Server operating system and version:  Red Hat Enterprise Linux Server release 7.9 (Maipo)

## Additional context

**Comment by nilmerg** [comment]
Hi,

this sounds a lot like #4853, though that's fixed in version 2.11.1. Are the times and dates in the event overview correct? Can you see results there fitting the time ranges the timeline doesn't show anything in?

**Comment by jre3brg** [comment]
Hi,
* Are the times and dates in the event overview correct? yes all dates and times are correct.
* Can you see results there fitting the time ranges the timeline doesn't show anything in? yes for the different intervals I can see the result when I select the date-time links.

**Comment by jre3brg** [comment]
Only data bubbles are not displayed.

[2022-07-27_10h36_48.pdf](https://github.com/Icinga/icingaweb2/files/9196580/2022-07-27_10h36_48.pdf)

**Comment by jre3brg** [comment]
Even with a fresh installation still not displaying data bubbles. I found this debug message when loading timeline.
 
2022-07-27T11:51:51+02:00 - DEBUG - Conversion method "retrieveTimestamp" for type definition "timestamp" does not exist

**Comment by jre3brg** [comment]
I updated my installation and replaced monitoring by icingadb, timeline not available on the new interface.
